import React from "react";
import "./Headshots.css";
import Headshot from "./Headshot";
const Headshots = () => {
	return (
		<div className="teamContainer" id="headshots">
			<h1>Meet the team</h1>
			<div className="org">
				<Headshot
					name="Disala"
					team="Co-Director"
					role=""
					insta="disala_desilva"
					linkedin="disaladesilva"
					website=""
				/>
				<Headshot name="Mingye" team="Co-Director" role="" insta="" linkedin="mingye-chen-ca" website=""/>
				<Headshot
					name="Steven"
					team="Community"
					role="Director"
					insta="_stevenli"
					linkedin="-steven"
					website=""
				/>
				<Headshot
					name="Fatimah"
					team="Design"
					role="Director"
					insta="fatimbit_v"
					linkedin="fatimah-vakily"
					website=""
				/>
				<Headshot
					name="Daniel"
					team="Development"
					role="Director"
					insta="arcanistzed"
					linkedin="arcanistzed"
					website=""
				/>
				<Headshot
					name="Ali"
					team="Finance"
					role="Co-Director"
					insta="notalibhangu"
					linkedin="ali-raza-bhangu-061274214"
					website=""
				/>
				<Headshot
					name="Pavly"
					team="Logistics"
					role="Co-Director"
					insta="pav_saleh"
					linkedin="pavly"
					website=""
				/>
				<Headshot
					name="Tomer"
					team="Logistics"
					role="Co-Director"
					insta="tomersz12"
					linkedin="tomersz12"
					website=""
				/>
				<Headshot
					name="Nyah"
					team="Marketing"
					role="Director"
					insta=""
					linkedin="nyah-wagner-a62064192"
					website=""
				/>
				<Headshot
					name="Kian"
					team="Sponsorship"
					role="Director"
					insta="kiiankiing"
					linkedin="kiansalehi"
					website=""
				/>
				<Headshot name="Brandon" team="Community" role="Coordinator" insta="" linkedin="" website="" />
				<Headshot
					name="Manaal"
					team="Community"
					role="Coordinator"
					insta="manaalm20"
					linkedin="manaal-mujeebuddin-ab2379199"
					website=""
				/>
				<Headshot name="Rafael" team="Community" role="Coordinator" insta="" linkedin="rafaelarif" website="" />
				<Headshot
					name="Saheen"
					team="Community"
					role="Coordinator"
					insta=""
					linkedin="saheen-jeyarajah"
					website=""
				/>
				<Headshot
					name="Emma"
					team="Design"
					role="Coordinator"
					insta="et.tangg"
					linkedin="emmatang-"
					website=""
				/>
				<Headshot name="Sakeena" team="Design" role="Coordinator" insta="" linkedin="" website="" />
				<Headshot name="Sheena" team="Design" role="Coordinator" insta="" linkedin="sheenaverana" website="" />
				<Headshot
					name="Arjuunan"
					team="Development"
					role="Coordinator"
					insta="itsarjuunan"
					linkedin="arjuunan"
					website=""
				/>
				<Headshot
					name="Aydin"
					team="Development"
					role="Coordinator"
					insta="ayay"
					linkedin="aydinyalcinkaya"
					website=""
				/>
				<Headshot
					name="Emilien"
					team="Development"
					role="Coordinator"
					insta=""
					linkedin=""
					website="https://edgie.emilien.ca/ "
				/>
				<Headshot
					name="Farabi"
					team="Development"
					role="Coordinator"
					insta="farabi.01"
					linkedin="mfarabi"
					website=""
				/>
				<Headshot name="Sacha" team="Development" role="Coordinator" insta="" linkedin="sacha-ars" website="" />
				<Headshot
					name="Stefan"
					team="Development"
					role="Coordinator"
					insta="steftodor"
					linkedin="todorovicstefan"
					website=""
				/>
				<Headshot name="Victor" team="Development" role="Coordinator" insta="" linkedin="" website="" />
				<Headshot
					name="Anna"
					team="Logistics"
					role="Coordinator"
					insta="annarie_88"
					linkedin="anna-schubert-689620202"
					website=""
				/>
				<Headshot
					name="Juan"
					team="Logistics"
					role="Coordinator"
					insta="jchhhiedrap"
					linkedin="jchiedrap"
					website=""
				/>
				<Headshot
					name="Philippe"
					team="Logistics"
					role="Coordinator"
					insta="philippegagne00"
					linkedin="p-gagne"
					website=""
				/>
				<Headshot
					name="Satrajit"
					team="Logistics"
					role="Coordinator"
					insta="satrajit.c"
					linkedin="satrajit-c"
					website=""
				/>
				<Headshot
					name="Thinula"
					team="Logistics"
					role="Coordinator"
					insta="Thinula_desilva"
					linkedin="thinula-de-silva-0a4202228"
					website=""
				/>
				<Headshot
					name="Andrea"
					team="Marketing"
					role="Coordinator"
					insta="dreatodor"
					linkedin="todorovic-andrea"
					website=""
				/>
				<Headshot
					name="Anjaliya"
					team="Marketing"
					role="Coordinator"
					insta="anjievs"
					linkedin="anjaliya-sonnilal-859586257"
					website=""
				/>
				<Headshot
					name="Kaitlyn"
					team="Marketing"
					role="Coordinator"
					insta="callherkdaddy"
					linkedin="kaitlyn-dompaul-3485a7180"
					website=""
				/>
				<Headshot
					name="Rabih"
					team="Marketing"
					role="Coordinator"
					insta="rabi3daoudd"
					linkedin="rabihdaoud"
					website=""
				/>
				<Headshot
					name="Saif"
					team="Marketing"
					role="Coordinator"
					insta="safesaif7"
					linkedin="saif-dine"
					website=""
				/>
				<Headshot name="Abbygail" team="Sponsorship" role="Coordinator" insta="" linkedin="" website=""/>
				<Headshot
					name="Erik"
					team="Sponsorship"
					role="Coordinator"
					insta="erik_ang_"
					linkedin="erik-ang-97773b260"
					website=""
				/>
				<Headshot
					name="Shreya"
					team="Sponsorship"
					role="Coordinator"
					insta="slanghe"
					linkedin="shreya-langhe"
					website=""
				/>
				<Headshot
					name="Sophie"
					team="Sponsorship"
					role="Coordinator"
					insta=""
					linkedin="sophie-tomlin-49163b20b"
					website=""
				/>
				<Headshot
					name="Zahra"
					team="Sponsorship"
					role="Coordinator"
					insta="zahrasnva"
					linkedin="zahra-suleymanova"
					website=""
				/>
			</div>
		</div>
	);
};

export default Headshots;
